version: '3.9'

services:
  api:
    build:
      context: .
      args:
        - DEV=${DEV}
    restart: always
    expose:
      - ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:8000"
    volumes:
      - ./api:/storeAPI/api
      - ./data:/storeAPI/data
    command: >
      sh -c "python ./api/manage.py makemigrations &&
             python ./api/manage.py migrate &&
             python ./api/manage.py addstores &&
             python ./api/manage.py addstoreshours &&
             python ./api/manage.py addstorestatus &&
             python ./api/manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db
      - redis

  db:
    image: bitnami/postgresql:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data:/storeAPI/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_SUPERUSER_PASS}

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  db-data: